[project]
name = "api"
version = "0.1.0"
description = "Paw Pages backend API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "cryptography>=50.0.1",
    "fastapi[standard]>=0.141.1",
    "pydantic-settings>=2.15.0",
    "httpx>=0.28.1",
    "openai>=3.19.2",
    "ocr-engine",
]

[tool.uv.sources]
ocr-engine = { path = "../ocr_engine", editable = true }
